---
# tasks file for deploy-default-apache_web
- block: #REDHAT BLOCK
    - name: Install apache for RedHat
      yum: name=httpd state=present
      
    - name: Start Web Server
      service: name=httpd state=started enabled=yes

  when: ansible_os_family == "RedHat"

- block: # DEBIAN BLOCK
    - name: Install apache for Debian
      apt: name=apache2 state=present

    - name: Start Web-Server
      service: name=apache2 state=started enabled=yes

  when: ansible_os_family == "Debian"

- name: Generate index.j2 to index.html
  template: src=index.j2 dest={{ destin_folder }}/index.html mode=0555
  notify:
    - Restart Apache
    - Restart Debian

- name: Copy files to Web Server
  copy: src={{ item }} dest={{ destin_folder }} mode=0555
  loop:
    - "bahamas.png"
    - "bulgaria.png"
    - "jordan.png"
    - "newzeland.png"
  notify:
    - Restart Apache
    - Restart Debian