---

- name: Копирование пакетов на хост
  hosts: 
  become: yes
  vars:
    KESL_SRV_LOCAL: 
    package_src_agent: "https://raw.githubusercontent.com/VadimGlinskiy/ansible/main/playbooks/kasper/klnagent64_14.2.0-23324_amd64.deb"
    package_dest_agent: "/home/klnagent64_14.2.0-23324_amd64.deb"
    package_src_client: "https://gitlab.com/VadimGlinsky/vadimglinsky/-/raw/main/kesl_12.0.0-6825_amd64.deb"
    package_dest_client: "/home/kesl_12.0.0-6825_amd64.deb"
  
  tasks:

  - name: Копирование пакета агента администрирования на хост
    get_url:
      url: "{{ package_src_agent }}"
      dest: "{{ package_dest_agent }}"
      owner: "ubuntu"
      group: "ubuntu"
      mode: '0644'

  - name: Установка агента
    apt:
      deb: "{{ package_dest_agent }}"
      state: present
      update_cache: yes

  - name: Создаем файл с ответами для скрипта[агент]
    blockinfile:
      path: /tmp/answers.txt
      create: yes
      block:  |
        KLNAGENT_SERVER={{ KESL_SRV_LOCAL }}
        KLNAGENT_AUTOINSTALL=Y
        EULA_ACCEPTED=Y
        KLNAGENT_PORT=14000
        KLNAGENT_USESSL=13000
        KLNAGENT_USESSL=1
        KLNAGENT_GW_MODE=0

  - name: Запускаем скрипт агента - postinstall.pl klnagent64
    shell: |
      export KLAUTOANSWERS=/tmp/answers.txt
      /opt/kaspersky/klnagent64/lib/bin/setup/postinstall.pl --autoinstall=$KLAUTOANSWERS


#  - name: Проверка работы агента
#    shell: "/opt/kaspersky/klnagent64/bin/klnagchk"
#    ignore_errors: yes

  
  - name: Копирование пакета клиента на хост
    get_url:
      url: "{{ package_src_client }}"
      dest: "{{ package_dest_client }}"
      owner: "ubuntu"
      group: "ubuntu"
      mode: '0644'

  - name: Установка пакета клиента
    apt:
      deb: "{{ package_dest_client }}"
      state: present
      update_cache: yes

  - name: Создаем файл с ответами для скрипта[клиент]
    blockinfile:
      path: /tmp/autoinstall.txt
      create: yes
      block: |
        EULA_AGREED=Yes
        PRIVACY_POLICY_AGREED=Yes
        USE_KSN=No
        LOCALE=en_US.UTF-8
        UPDATE_EXECUTE=No
        GROUP_CLEAN=No
        USE_GUI=Yes
        KERNEL_SRCS_INSTALL=No
  
  - name: Скрипт установки клиента - postinstall.pl
    shell: "/opt/kaspersky/kesl/bin/kesl-setup.pl --autoinstall=/tmp/autoinstall.txt"
    ignore_errors: yes

  - name: Задаем айпи-адрес сервера
    shell: "/opt/kaspersky/klnagent64/bin/klmover -address {{ KESL_SRV_LOCAL }}"
    become: yes

Логика:

#установка агента
#sudo apt install ./klnagent64_14.2.0-23324_amd64.deb
#запустить скрипт из вывода установки
#Server - {{ KESL_SRV_LOCAL }} # остается для истории 
#Server SSL ports: '13000'
#Server ports: '14000'
#Проверка - /opt/kaspersky/klnagent64/bin/klnagchk

#установка клиента
#sudo apt install ./kesl_12.0.0-6825_amd64.deb
#/opt/kaspersky/kesl/bin/kesl-setup.pl

#В самом конце прописать
# /opt/kaspersky/klnagent64/bin/klmover -address 10.4.22.152
