---
all:
  hosts:
    node0:
      ansible_host: 192.168.174.134
      ansible_user: ubuntu
      consul_node_role: server
    node1:
      ansible_host: 192.168.174.135
      ansible_user: ubuntu
      consul_node_role: server
    node2:
      ansible_host: 192.168.174.136
      ansible_user: ubuntu
      consul_node_role: server
  
  vars:
    ansible_python_interpreter: /usr/bin/python3
    consul_bootstrap_expect: true
    become: yes

  children:
    postgresql_servers:
      hosts:
        node0:
        node1:
        node2:
    
    consul_servers:
      hosts:
        node0:
        node1:
        node2:
    
    patroni_servers:
      hosts:
        node0:
        node1:
        node2: