---
# Установка веб-сервера, использование модуля yum(для Redhat)
# также модуля service, который управляет демонами, автозагрузкой
- name: Установка веб-сервера apache
  hosts: PROD
  become: yes

  tasks:
  
  - name: Установка
    yum: name=httpd state=present

  - name: Старт сервиса и правка автозапуска
    service: name=httpd state=started enabled=yes


