---
# Установка сервера, копирование туда .html файла
# использование nofify и handlers, чтобы сервер делал reload при каждом пуше изменений в файл
- name: Install apache and upload my file
  hosts: cent
  become: yes

  vars:
    source_file: ../index.html
    destin_file: /var/www/html

  tasks:
    - name: Install webserver 
      yum: name=httpd state=present

    - name: Copy .html file to server
      copy: src={{ source_file }} dest={{ destin_file }} mode=0555
      notify: Restart server

    - name: Start service and boot
      service: name=httpd state=started enabled=yes



  handlers:
    - name: Restart server
      service: name=httpd state=reloaded
